### PR TITLE
feat: lateral column alias reference (#507)

### LINKED ISSUE #507: Support Lateral Column Alias Reference Analyzing
**SQL**
```sql
insert into public.tgt_tbl1
(
    id
)
select
    sq.id
from
    (
        select
            name      as user_name,
            user_name as id -- backward reference
        from
            public.src_tbl1
    ) sq
;
```

**To Reproduce**
*Note here we refer to SQL provided in prior step as stored in a file named `test.sql`*

```python
from sqllineage.runner import LineageRunner
with open("test.sql") as f:
    sql = f.read()
lr = LineageRunner(sql, dialect='redshift')
lr.print_column_lineage()
```
```
public.tgt_tbl1.id <- sq.id <- public.src_tbl1.user_name
```

**Expected behavior**
```
public.tgt_tbl1.id <- sq.id <- public.src_tbl1.name
```
**Python version (available via `python --version`)**
 - 3.11.5

**SQLLineage version (available via `sqllineage --version`):**
 - 1.4.9

### PR DESCRIPTION
**Pull request by maoxingda**
Closes #507

### CODE REVIEW

**Review by reata — COMMENTED** [review]
Thanks for the contribution. The code looks good to me. 

One question: can we extend the current logic to handle lateral column alias at top level (not in a subquery), or do you plan to handle that in separate PR?
```sql
insert into public.tgt_tbl1
select
    name      as user_name,
    user_name as id -- backward reference
from
    public.src_tbl1
;
```

**Comment by maoxingda** [comment]
Thank you for your response. I'm not sure if I can handle it, but I'll give it a try.

**Comment by reata** [comment]
We can also merge this and not closing #507, if top-level lateral column alias takes too much effort.

Just let me know your conclusion. Thanks for taking time investigating.

**Comment by maoxingda** [comment]
If it can be like this, that would be the best.

**Comment by maoxingda** [comment]
I will try to expand at top level.

**Comment by maoxingda** [comment]
> We can also merge this and not closing #507, if top-level lateral column alias takes too much effort.
> 
> Just let me know your conclusion. Thanks for taking time investigating.

It seems that it doesn't require too much effort.

**Pull request merged**
